# Site settings
title: SnowiQ App User Manual
author: 
name: EBTSnowiQ
description: "SnowiQ app user manual on GH-Pages contact@eastbanctech.com"
email: contact@eastbanctech.com

# Build settings
remote_theme: jekyll/minima
minima:
  skin: dark


