# Site settings
title: SnowiQ App User Manual
author: 
name: Eastbanc Technologies
description: "SnowiQ app user manual on GH-Pages"
email: contact@eastbanctech.com

# Build settings
remote_theme: jekyll/hyde


