# Site settings
title: SnowiQ App User Manual
author: Eastbanc Technologies
  email: contact@eastbanctech.com
description: "SnowiQ app user manual on GH-Pages""

# Build settings
remote_theme: jekyll/minima
